apiVersion : apps/v1
kind: Deployment
metadata:
  name: "mxaks-5733"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: "mxaks-5733"
  template:
    metadata:
      labels:
        app: "mxaks-5733"
    spec:
      containers:
        - name: "mxaks-5733"
          image: "mxacr.azurecr.io/mxaks"
          ports:
          - containerPort: 80