apiVersion: v1
kind: Service
metadata:
    name: "mxaks-5733"
    labels:
        app: "mxaks-5733"
spec:
    type: LoadBalancer
    ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http
    selector:
        app: "mxaks-5733"