on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    
    - uses: azure/docker-login@v1
      with:
        login-server: mxacr.azurecr.io
        username: ${{ secrets.acr_mxacr_username }}
        password: ${{ secrets.acr_mxacr_password }}
    
    - name: Build and push image to ACR
      id: build-image
      run: |
        docker build "$GITHUB_WORKSPACE/Demo.Kubernetes.Deployment" -f  "Demo.Kubernetes.Deployment/Dockerfile" -t mxacr.azurecr.io/mxaks:${{ github.sha }} --label dockerfile-path=Demo.Kubernetes.Deployment/Dockerfile
        docker push mxacr.azurecr.io/mxaks:${{ github.sha }}
    
    - uses: azure/k8s-set-context@v1
      with:
         kubeconfig: ${{ secrets.aks_mxaks_kubeConfig }}
      id: login
    
    - name: Create namespace
      run: |
        namespacePresent=`kubectl get namespace | grep default | wc -l`
        if [ $namespacePresent -eq 0 ]
        then
            echo `kubectl create namespace default`
        fi

    - uses: azure/k8s-create-secret@v1
      with:
        namespace: default
        container-registry-url: mxacr.azurecr.io
        container-registry-username: ${{ secrets.acr_mxacr_username }}
        container-registry-password: ${{ secrets.acr_mxacr_password }}
        secret-name: mxaksdockerauth
       
    - uses: azure/k8s-deploy@v1.2
      with:
        namespace: default
        manifests: |
          manifests/deployment.yml
          manifests/service.yml
        images: |
          mxacr.azurecr.io/mxaks:${{ github.sha }}
        imagepullsecrets: |
          mxaksdockerauth
